export const ADD_CONTENT = "ADD_CONTENT";
export const GET_CONTENT = "GET_CONTENT";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const DELETE_CONTENT = "DELETE_CONTENT";


export const LATEST_CONTENT = "LATEST_CONTENT";
export const OLD_CONTENT = "OLD_CONTENT";
export const DEFAULT_CONTENT = "DEFAULT_CONTENT";

export const TOP_RATED_CONTENT = "TOP_RATED_CONTENT";
export const LOW_RATED_CONTENT = "LOW_RATED_CONTENT";

export const SET_BLOG_VALUE = "SET_BLOG_VALUE";